version: 2
jobs:
  gather-dependencies-and-freeze:
    machine: true
    steps:
      - checkout
      - run:
          name: Use python 3
          command: pyenv global 3.7.0
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv env && source env/bin/activate
      - run: 
          name: pip install dependencies
          command: pip install -r requirements.txt
      - run:
          name: pip freeze
          command: pip freeze

workflows:
  version: 2
  deps-and-freeze:
    jobs:
      - gather-dependencies-and-freeze