version: 2
jobs:
  gather-dependencies-and-freeze:
    machine: true

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-{{ checksum "requirements.txt" }}
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv venv && source venv/bin/activate
      - run: 
          name: pip install dependencies
          command: pip install -r requirements.txt
      - run:
          name: pip freeze
          command: pip freeze
      - save_cache:
          key: v2-{{ checksum "requirements.txt" }}
          paths:
            - venv

workflows:
  version: 2
  deps-and-freeze:
    jobs:
      - gather-dependencies-and-freeze