version: 2
jobs:
  gather-dependencies-and-freeze:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv env && source env/bin/activate
      - run: 
          name: pip install dependencies
          command: pip install -r requirements.txt
      - run:
          name: pip freeze
          command: pip freeze
      