version: 2
jobs:
  gather-dependencies-and-freeze:
    docker:
      - image: circleci/python:buster
    
    steps:
      - checkout
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv env && source env/bin/activate
      - run: 
          name: pip install dependencies
          command: pip install -r requirements.txt
      - run:
          name: pip freeze
          command: pip freeze

workflows:
  version: 2
  deps-and-freeze:
    jobs:
      - gather-dependencies-and-freeze