version: 2
jobs:
  gather-dependencies-and-freeze:
    machine:
      image: circleci/classic:201808-01

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-{{ checksum "requirements.txt" }}
      - run:
          name: Switch to Python 3.7
          command: |
            pyenv versions
            pyenv global 3.7.0
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv venv && source venv/bin/activate
      - run: 
          name: pip install dependencies
          command: pip install -r requirements.txt
      - run:
          name: pip freeze
          command: pip freeze
      - save_cache:
          key: v3-{{ checksum "requirements.txt" }}
          paths:
            - venv

workflows:
  version: 2
  deps-and-freeze:
    jobs:
      - gather-dependencies-and-freeze