version: 2
jobs:
  gather-dependencies-and-freeze:
    machine: true
    steps:
      - checkout
      - run:
          name: Make virtualenv folder and activate
          command: virtualenv env && source env/bin/activate
      - run: 
          name: pip install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: pip freeze
          command: pip3 freeze

workflows:
  version: 2
  deps-and-freeze:
    jobs:
      - gather-dependencies-and-freeze